/*
 Kidcompy - a virtual computer for kids
 Copyright (C) 2016  Woldrich, Inc.

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

"use strict";

/**
 * State codes that govern what the KidcompyHost is working on right now
 * @enum {number}
 */
var KidcompyHostState = {
  /** Okay to flip buffers */
  FLIP_BUFFERS: 0,
  /** Process any queued InputEvents from the browser that we are listening to */
  PROCESS_INPUTS: 1,
  /** Run any per-frame scripts (like Tasty or machine code) */
  RUN_SCRIPTS: 2,
  /** Process any queued draw events generated by Tasty or machine code */
  RENDER_BUFFERS: 3
};

module.exports = KidcompyHostState;
